version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"  
    restart: always  
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db   
volumes:
  postgres_data:
    driver: local      