# Generated by Django 3.2.8 on 2021-10-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211019_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='id_activity',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
