# Generated by Django 3.2.8 on 2021-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211023_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_lms',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
