# Generated by Django 3.2.8 on 2021-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person_id_lms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object',
            field=models.CharField(max_length=400),
        ),
    ]
